apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-pipeline-deployment
  namespace: __NAMESPACE__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-pipeline
  template:
    metadata:
      labels:
        app: k8s-pipeline
    spec:
      containers:
      - name: k8s-pipeline
        image: __IMAGE__
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-pipeline-service
  namespace: __NAMESPACE__
spec:
  selector:
    app: k8s-pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
