apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-pipeline-deployment
  namespace: __NAMESPACE__
  labels:
    app: k8s-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-pipeline
  template:
    metadata:
      labels:
        app: k8s-pipeline
    spec:
      containers:
      - name: k8s-pipeline
        image: __IMAGE__
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-pipeline-service
  namespace: __NAMESPACE__
  labels:
    app: k8s-pipeline
spec:
  selector:
    app: k8s-pipeline
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
