apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      containers:
        - name: basic-app-container
          image: myapp:latest  # This will be overwritten by your Jenkins pipeline build tag
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: basic-app-service
spec:
  type: NodePort
  selector:
    app: basic-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
