# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: jenkins-kind-cluster
networking:
  # This makes the API server accessible from host and containers
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  # Disable default CNI to avoid conflicts
  disableDefaultCNI: false
  # Pod subnet (optional, but good to be explicit)
  podSubnet: "10.244.0.0/16"
  # Service subnet (optional, but good to be explicit)  
  serviceSubnet: "10.96.0.0/12"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # NodePort range mapping
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
